---
 - name: Playbook for Variables
   hosts: all
   become: yes

   vars:
       message1: Privet
       message2: World
       secret  : sdgsdgsdgdf

   tasks:
      - name: Print Secret Variable
        debug:
          var: secret

      - debug:
          msg: "Sekretnoe slovo: {{ secret }}"

      - debug:
          msg: "Vladelec Servera {{ owner }}"

      - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

      - debug:
          var: full_message

      - debug:
          msg: "{{ ansible_distribution }}"

      - debug:
          var: ansible_distribution

      - shell: uptime
        register: results

      - debug:
          var: results  
